"""Initial migration - create all tables

Revision ID: 6d515a4d8513
Revises: 
Create Date: 2026-01-16 17:21:32.761781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d515a4d8513'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False, comment='Firebase 사용자 UID'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일 주소'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='표시 이름'),
    sa.Column('photo_url', sa.Text(), nullable=True, comment='프로필 이미지 URL'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='인증 제공자 (google/apple/kakao)'),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False, comment='푸시 알림 활성화 여부'),
    sa.Column('fcm_token', sa.Text(), nullable=True, comment='FCM 토큰'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 로그인 일시'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='계정 활성화 상태'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('panels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='소유자 사용자 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='패널/발전소 이름'),
    sa.Column('description', sa.Text(), nullable=True, comment='설명'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='위치 (주소)'),
    sa.Column('rtsp_url', sa.Text(), nullable=True, comment='RTSP 스트림 URL'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='패널 상태 (active/inactive/error/maintenance)'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='위도'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='경도'),
    sa.Column('grid_nx', sa.Integer(), nullable=True, comment='기상청 격자 X'),
    sa.Column('grid_ny', sa.Integer(), nullable=True, comment='기상청 격자 Y'),
    sa.Column('capacity_kw', sa.Float(), nullable=True, comment='발전 용량 (kW)'),
    sa.Column('panel_count', sa.Integer(), nullable=True, comment='패널 개수'),
    sa.Column('thumbnail_url', sa.Text(), nullable=True, comment='대표 이미지 URL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 일시'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panels_status'), 'panels', ['status'], unique=False)
    op.create_index(op.f('ix_panels_user_id'), 'panels', ['user_id'], unique=False)
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False, comment='패널 ID'),
    sa.Column('report_date', sa.Date(), nullable=False, comment='리포트 날짜'),
    sa.Column('total_detections', sa.Integer(), nullable=False, comment='총 탐지 건수'),
    sa.Column('total_defects', sa.Integer(), nullable=False, comment='결함 탐지 건수'),
    sa.Column('total_soiling', sa.Integer(), nullable=False, comment='오염 탐지 건수'),
    sa.Column('avg_soiling_area', sa.Float(), nullable=True, comment='평균 오염 영역 비율 (%)'),
    sa.Column('max_soiling_area', sa.Float(), nullable=True, comment='최대 오염 영역 비율 (%)'),
    sa.Column('estimated_loss_kwh', sa.Float(), nullable=True, comment='추정 발전 손실량 (kWh)'),
    sa.Column('estimated_loss_krw', sa.Float(), nullable=True, comment='추정 손실 금액 (원)'),
    sa.Column('cleaning_recommended', sa.Boolean(), nullable=False, comment='청소 권고 여부'),
    sa.Column('weather_summary', sa.Text(), nullable=True, comment='날씨 요약'),
    sa.Column('had_rain', sa.Boolean(), nullable=False, comment='강우 발생 여부'),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='상세 요약 데이터 (JSON)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 일시'),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='일간 분석 리포트'
    )
    op.create_index(op.f('ix_daily_reports_panel_id'), 'daily_reports', ['panel_id'], unique=False)
    op.create_index(op.f('ix_daily_reports_report_date'), 'daily_reports', ['report_date'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False, comment='패널 ID'),
    sa.Column('defect_type', sa.String(length=20), nullable=False, comment='결함 유형 (defect/soiling/normal)'),
    sa.Column('defect_subtype', sa.String(length=30), nullable=True, comment='결함 세부 유형'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='탐지 신뢰도 (0.0 ~ 1.0)'),
    sa.Column('bbox_x', sa.Integer(), nullable=False, comment='바운딩 박스 X 좌표'),
    sa.Column('bbox_y', sa.Integer(), nullable=False, comment='바운딩 박스 Y 좌표'),
    sa.Column('bbox_width', sa.Integer(), nullable=False, comment='바운딩 박스 너비'),
    sa.Column('bbox_height', sa.Integer(), nullable=False, comment='바운딩 박스 높이'),
    sa.Column('snapshot_url', sa.Text(), nullable=True, comment='스냅샷 이미지 URL'),
    sa.Column('frame_number', sa.Integer(), nullable=True, comment='프레임 번호'),
    sa.Column('area_percentage', sa.Float(), nullable=True, comment='결함 영역 비율 (%)'),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='탐지 일시'),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_defect_type'), 'detections', ['defect_type'], unique=False)
    op.create_index(op.f('ix_detections_detected_at'), 'detections', ['detected_at'], unique=False)
    op.create_index(op.f('ix_detections_panel_id'), 'detections', ['panel_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('detection_id', sa.Integer(), nullable=True, comment='연결된 탐지 결과 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='수신 사용자 ID'),
    sa.Column('alert_type', sa.String(length=20), nullable=False, comment='알림 유형'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='알림 제목'),
    sa.Column('message', sa.Text(), nullable=False, comment='알림 내용'),
    sa.Column('image_url', sa.Text(), nullable=True, comment='알림 이미지 URL'),
    sa.Column('deep_link', sa.String(length=500), nullable=True, comment='딥링크 URL'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='읽음 여부'),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='발송 일시'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='읽음 일시'),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_detection_id'), 'alerts', ['detection_id'], unique=False)
    op.create_index(op.f('ix_alerts_is_read'), 'alerts', ['is_read'], unique=False)
    op.create_index(op.f('ix_alerts_sent_at'), 'alerts', ['sent_at'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_sent_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_read'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_detection_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_detections_panel_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_detected_at'), table_name='detections')
    op.drop_index(op.f('ix_detections_defect_type'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_daily_reports_report_date'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_panel_id'), table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index(op.f('ix_panels_user_id'), table_name='panels')
    op.drop_index(op.f('ix_panels_status'), table_name='panels')
    op.drop_table('panels')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
