"""add_analysis_session_model

Revision ID: 7cf9a3383005
Revises: 6326b87ee907
Create Date: 2026-02-04 14:17:59.026484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf9a3383005'
down_revision: Union[str, Sequence[str], None] = '6326b87ee907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False, comment='패널 ID'),
    sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED', 'FAILED', name='analysis_status_enum', native_enum=False), nullable=False, comment='분석 상태 (processing/completed/failed)'),
    sa.Column('type', sa.Enum('CCTV', 'DRONE', name='monitoring_type_enum', native_enum=False), nullable=False, comment='모니터링 유형 (cctv/drone)'),
    sa.Column('original_image_url', sa.Text(), nullable=True, comment='원본 이미지 URL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='분석 요청 일시'),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_sessions_created_at'), 'analysis_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_sessions_panel_id'), 'analysis_sessions', ['panel_id'], unique=False)
    op.create_index(op.f('ix_analysis_sessions_status'), 'analysis_sessions', ['status'], unique=False)
    op.add_column('detections', sa.Column('analysis_session_id', sa.UUID(), nullable=True, comment='분석 세션 ID'))
    op.create_index(op.f('ix_detections_analysis_session_id'), 'detections', ['analysis_session_id'], unique=False)
    op.create_foreign_key(None, 'detections', 'analysis_sessions', ['analysis_session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detections', type_='foreignkey')
    op.drop_index(op.f('ix_detections_analysis_session_id'), table_name='detections')
    op.drop_column('detections', 'analysis_session_id')
    op.drop_index(op.f('ix_analysis_sessions_status'), table_name='analysis_sessions')
    op.drop_index(op.f('ix_analysis_sessions_panel_id'), table_name='analysis_sessions')
    op.drop_index(op.f('ix_analysis_sessions_created_at'), table_name='analysis_sessions')
    op.drop_table('analysis_sessions')
    # ### end Alembic commands ###
