"""add_mask_column

Revision ID: a1b2c3d4e5f6
Revises: 6326b87ee907
Create Date: 2026-02-09 14:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '6326b87ee907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('mask', sa.Text(), nullable=True, comment='세그멘테이션 마스크 Polygon (JSON)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detections', 'mask')
    # ### end Alembic commands ###
