"""add_ai_briefing_fields_to_daily_report

Revision ID: ed69797c9907
Revises: 6d515a4d8513
Create Date: 2026-01-29 15:37:08.662758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed69797c9907'
down_revision: Union[str, Sequence[str], None] = '6d515a4d8513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_reports', sa.Column('ai_solution_type', sa.Text(), nullable=True, comment='AI 솔루션 타입 (good/caution/danger)'))
    op.add_column('daily_reports', sa.Column('ai_solution_title', sa.Text(), nullable=True, comment='AI 솔루션 한줄 요약'))
    op.add_column('daily_reports', sa.Column('ai_solution_content', sa.Text(), nullable=True, comment='AI 솔루션 상세 설명'))
    op.add_column('daily_reports', sa.Column('ai_action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AI 추천 액션 아이템 목록'))
    op.add_column('daily_reports', sa.Column('anomalies', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='오늘 특이사항 목록'))
    op.add_column('daily_reports', sa.Column('weather_forecast', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='내일 날씨 예보 정보'))
    op.add_column('daily_reports', sa.Column('ai_generated_at', sa.DateTime(timezone=True), nullable=True, comment='AI 솔루션 생성 시각'))
    op.alter_column('detections', 'defect_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DEFECT', 'SOILING', 'NORMAL', name='defect_type_enum', native_enum=False),
               existing_comment='결함 유형 (defect/soiling/normal)',
               existing_nullable=False)
    op.alter_column('detections', 'defect_subtype',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('CRACK', 'HOTSPOT', 'BROKEN_CELL', 'DELAMINATION', 'DUST', 'BIRD_DROP', 'LEAF', 'SNOW', 'UNKNOWN', name='defect_subtype_enum', native_enum=False),
               existing_comment='결함 세부 유형',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detections', 'defect_subtype',
               existing_type=sa.Enum('CRACK', 'HOTSPOT', 'BROKEN_CELL', 'DELAMINATION', 'DUST', 'BIRD_DROP', 'LEAF', 'SNOW', 'UNKNOWN', name='defect_subtype_enum', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_comment='결함 세부 유형',
               existing_nullable=True)
    op.alter_column('detections', 'defect_type',
               existing_type=sa.Enum('DEFECT', 'SOILING', 'NORMAL', name='defect_type_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_comment='결함 유형 (defect/soiling/normal)',
               existing_nullable=False)
    op.drop_column('daily_reports', 'ai_generated_at')
    op.drop_column('daily_reports', 'weather_forecast')
    op.drop_column('daily_reports', 'anomalies')
    op.drop_column('daily_reports', 'ai_action_items')
    op.drop_column('daily_reports', 'ai_solution_content')
    op.drop_column('daily_reports', 'ai_solution_title')
    op.drop_column('daily_reports', 'ai_solution_type')
    # ### end Alembic commands ###
